# -*- coding: utf-8 -*-
"""Copy of Support Vector Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LRp_N0M3A9qsgo29SoopVDQREStUfV0m

# Support Vector Regression (SVR) — Exact Return Prediction

## Import
Import all libraries needed for data handling, modelling, evaluation, and plotting.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

from sklearn.svm import SVR
from sklearn.model_selection import TimeSeriesSplit, RandomizedSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.inspection import permutation_importance

"""## File Upload
Upload the zipped train/test dataset from local storage and extract it into the Colab runtime.
"""

from google.colab import files
import zipfile

uploaded = files.upload()  # select train_test_dataset.zip

with zipfile.ZipFile("train_test_dataset.zip", "r") as zip_ref:
    zip_ref.extractall(".")

"""## Load Datafile
Load the pre-split, pre-scaled train/test CSVs. SVR is a distance/kernel-based model, so it needs the scaled feature set (Toolbox B), not the raw/unscaled one.
"""

X_train = pd.read_csv("X_train_trans_scaled.csv")
X_test  = pd.read_csv("X_test_trans_scaled.csv")
y_train = pd.read_csv("y_train.csv").squeeze()
y_test  = pd.read_csv("y_test.csv").squeeze()

print("X_train:", X_train.shape, "| X_test:", X_test.shape)

"""## Evaluation Function
Reusable function that reports MAE (4 dp), RMSE (4 dp), R² (4 dp), and Directional Accuracy (2 dp), so every model in the team's notebooks reports metrics in the same format.
"""

def evaluate(y_true, y_pred, label="Model"):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    da = (np.sign(y_pred) == np.sign(y_true)).mean() * 100

    print(f"=== {label} — Test Set Performance ===")
    print(f"MAE  : {mae:.4f}")
    print(f"RMSE : {rmse:.4f}")
    print(f"R2   : {r2:.4f}")
    print(f"DA   : {da:.2f}%")

    return {"MAE": mae, "RMSE": rmse, "R2": r2, "DA": da}

"""## Main Modelling
Hyperparameter search with `RandomizedSearchCV` over `TimeSeriesSplit` folds (not standard k-fold, which would let future folds leak into training on chronological data), then fit the best estimator on the full training set and evaluate it on the held-out test set.
"""

param_grid = [
    {'kernel': ['rbf'], 'C': [0.01, 0.1, 1, 10, 50, 100],
     'epsilon': [0.05, 0.1, 0.3, 0.5, 0.8], 'gamma': ['scale', 'auto', 0.01, 0.1]},
    {'kernel': ['linear'], 'C': [0.01, 0.1, 1, 10, 50, 100],
     'epsilon': [0.05, 0.1, 0.3, 0.5, 0.8]}
]

svr_search = RandomizedSearchCV(
    SVR(), param_grid, n_iter=30, cv=TimeSeriesSplit(n_splits=5),
    scoring='neg_mean_absolute_error', n_jobs=-1, random_state=42
)
svr_search.fit(X_train, y_train)

svr_final = svr_search.best_estimator_
print("Best params:", svr_search.best_params_)

y_pred_eval = svr_final.predict(X_test)
metrics = evaluate(y_test, y_pred_eval, label="Final SVR")

"""Observations & Insights: An optimal C of 0.01 and epsilon of 0.8 indicates a strong regularization penalty within the RBF kernel.
- In financial time-series forecasting, features often exhibit multi-collinearity and noise.
- A low C value prevents overfitting on historical market noise by prioritizing a wider margin and minimizing the influence of individual data points.
> Error Metrics (MAE: 0.6389, RMSE: 0.9163): The relatively low error rates confirm robust generalization on the test set, proving the chosen parameters successfully managed the noise-to-signal ratio.
> R2 Score (-0.0148): Near-zero R2 reflects the random-walk nature of daily financial returns, showing that even non-linear kernels struggle to capture exact point-by-point return variance.
. Directional Accuracy (60.56%): Heavily outperforms a 50% random coin toss, proving that the RBF kernel's feature inputs successfully capture predictive market timing signals.
"""

import ipywidgets as widgets
from IPython.display import display, clear_output
import numpy as np
import pandas as pd
import pickle

# ==========================================
# 1. LOAD EXPORTED SVR MODEL AND PREPROCESSORS
# ==========================================
try:
    # Load SVR Model
    with open('svr_final_model.pkl', 'rb') as file:
        svr_model = pickle.load(file)

    # Load the unified teammate preprocessors dictionary instead of individual files
    with open('preprocessors.pkl', 'rb') as f:
        preprocessors = pickle.load(f)

    print("✅ SVR Model and Preprocessors successfully loaded.")
except FileNotFoundError:
    print("❌ ERROR: Please ensure 'svr_final_model.pkl' and 'preprocessors.pkl' are uploaded to Colab.")

# ==========================================
# 2. BUILD THE USER INTERFACE WIDGETS
# ==========================================
print("=== 🔮 SVR: PREDICTION SANDBOX (TOOLBOX B) ===")

price_input = widgets.FloatText(value=60000.0, description='Price Lag1 (₹):', style={'description_width': 'initial'})
vol_input = widgets.FloatText(value=51877.0, description='Volume Lag1:', style={'description_width': 'initial'})
ret_input = widgets.FloatText(value=0.02, description='Return Lag1 (%):', style={'description_width': 'initial'})
vol7_input = widgets.FloatText(value=0.85, description='Vol 7d:', style={'description_width': 'initial'})
vol30_input = widgets.FloatText(value=0.99, description='Vol 30d:', style={'description_width': 'initial'})
anomaly_input = widgets.Dropdown(options=[('Normal Day (0)', 0), ('Anomaly (1)', 1)], value=0, description='Is Anomaly:', style={'description_width': 'initial'})

predict_btn = widgets.Button(description="Generate SVR Prediction", button_style='success', icon='check')
output_display = widgets.Output()

left_box = widgets.VBox([price_input, ret_input, vol7_input])
right_box = widgets.VBox([vol_input, anomaly_input, vol30_input])
ui = widgets.HBox([left_box, right_box])

# ==========================================
# 3. DEFINE THE PREDICTION LOGIC
# ==========================================
def on_predict_click(b):
    with output_display:
        clear_output()
        print("Processing input data using preprocessors.pkl...")

        p_lag = price_input.value
        v_lag = vol_input.value
        r_lag = ret_input.value
        v7 = vol7_input.value
        v30 = vol30_input.value
        is_anom = anomaly_input.value

        try:
            # A. Toolbox B Transformations using preprocessors.pkl keys
            price_log = np.log(p_lag)
            price_scaled = (price_log - preprocessors['price_mean']) / preprocessors['price_std']
            vol_scaled   = preprocessors['pt_vol'].transform([[v_lag]])[0,0]
            ret_scaled   = preprocessors['scaler_return'].transform([[r_lag]])[0,0]
            vol7_scaled  = preprocessors['pt_vol7'].transform([[v7]])[0,0]
            vol30_scaled = preprocessors['pt_vol30'].transform([[v30]])[0,0]

            # Construct the final scaled array in the correct Toolbox B order
            scaled_array = np.array([[price_scaled, vol_scaled, ret_scaled, vol7_scaled, vol30_scaled, is_anom]])

            # B. SVR Prediction
            pred_return = svr_model.predict(scaled_array)[0]

            # C. Price Reconstruction
            pred_price = p_lag * (1 + (pred_return / 100))

            print("-" * 40)
            print("✅ SVR PREDICTION SUCCESSFUL")
            print(f"-> Predicted Daily Return : {pred_return:+.4f}%")
            print(f"-> Reconstructed Price    : ₹{pred_price:,.2f}")
            print("-" * 40)

        except Exception as e:
            print(f"❌ Error during prediction: {e}")

predict_btn.on_click(on_predict_click)
display(ui, predict_btn, output_display)

"""## Feature Importance
Permutation importance on the test set (SVR has no native `coef_`/`feature_importances_` for the RBF kernel, so permutation importance is used instead). Values only, in table form.
"""

perm = permutation_importance(
    svr_final, X_test, y_test,
    n_repeats=30, random_state=42, scoring='neg_mean_absolute_error'
)

feature_importance_df = pd.DataFrame({
    'Feature': X_test.columns,
    'Importance': perm.importances_mean
}).sort_values('Importance', ascending=False).reset_index(drop=True)

display(feature_importance_df)

"""## Visualization

### Cumulative Graph
Position size scales with the predicted return itself (not just its sign), so a larger predicted move gets a larger position and a small/near-zero prediction gets a small position. Cumulative return of this magnitude-weighted strategy is plotted against a buy-and-hold benchmark, both compounded with `cumprod`. Uses the one-step test-set predictions (`y_pred_eval`) — not autoregressive.
"""

# Magnitude-based strategy: use predicted value as position size
y_dec = y_test.values / 100
pred_dec = y_pred_eval / 100
mag_daily = pred_dec * y_dec * 100   # daily return in percent
mag_cum_pct = (1 + mag_daily / 100).cumprod() - 1

# Buy & Hold benchmark
buy_hold_cum_pct = (1 + y_test.values / 100).cumprod() - 1

plt.figure(figsize=(12, 4.5))
plt.plot(buy_hold_cum_pct, label='Buy & Hold', color='gray', lw=1)
plt.plot(mag_cum_pct * 100, label='SVR Magnitude‑based Strategy', color='blue', lw=1.2)
plt.axhline(0, color='red', linestyle='--', lw=0.6)
plt.xlabel('Trading Days')
plt.ylabel('Cumulative Return (%)')
plt.title('Magnitude‑based SVR Strategy vs. Buy & Hold')
plt.legend()
plt.show()

"""### Observations & Insights from the Graph
- **The Market (Gray Line)**: Exhibits massive growth, rising from 0% to nearly 140% cumulative return over the 600 trading days, characterized by strong upward momentum, particularly past index 400.
- **The SVR Forecast (Blue Line)**: Stays extremely close to the baseline, capturing very little of the overall market movement.
> **Why this happens**: Because the SVR model uses a low **C (0.01)** and high **epsilon (0.8)**, it aggressively avoids making aggressive directional wagers to protect against market noise. It prioritizes capturing a wider margin and minimizing the influence of outliers, resulting in a safe but highly conservative curve that stays flat during the explosive 140% market rally.

## Actual and Predicted Line Graph for Exact Return

Day-by-day line plot of the actual vs. predicted exact return on the test set.
"""

plt.figure(figsize=(12, 4))
plt.plot(y_test.values, label='Actual Exact_Return', color='steelblue', linewidth=0.8)
plt.plot(y_pred_eval, label='Predicted Exact_Return', color='darkorange', linewidth=0.8, alpha=0.85)
plt.axhline(0, color='red', linestyle='--', linewidth=0.7)
plt.legend()
plt.title('Final SVR: Actual vs Predicted Exact_Return (Test Set)')
plt.tight_layout()
plt.show()

"""### Observations & Insights from the Graph:

- **The Volatility (Steelblue Line)**: Swings violently up and down daily, with regular market shocks stretching between -5% and +3%.

- **The Prediction Line (Orange Line)**: Appears as an almost perfectly flat horizontal line running along the 0% baseline.

> **Why this happens**: Predicting exact day-to-day financial returns in noisy asset markets is notoriously difficult. Because the SVR model uses a strong regularization penalty (low C and high epsilon), the safest mathematical choice for the model on any given day is to predict close to 0% (the median expected return), completely filtering out day-to-day market noise to minimize overall error.

## Extra: TimeSeriesSplit Stability Check
SVR-specific sanity check. Re-fits the *already-chosen* hyperparameters (no new search) across each `TimeSeriesSplit` fold to confirm performance is stable across sequential periods, rather than an artifact of one particular train/test split.
"""

def fold_metrics(y_true, y_pred_):
    mae_ = mean_absolute_error(y_true, y_pred_)
    rmse_ = np.sqrt(mean_squared_error(y_true, y_pred_))
    da_ = (np.sign(y_pred_) == np.sign(y_true)).mean() * 100
    return mae_, rmse_, da_

X_full = pd.concat([X_train, X_test], axis=0).reset_index(drop=True)
y_full = pd.concat([y_train, y_test], axis=0).reset_index(drop=True)

tscv = TimeSeriesSplit(n_splits=5)
fold_results = []

for fold, (train_idx, test_idx) in enumerate(tscv.split(X_full)):
    X_tr, X_te = X_full.iloc[train_idx], X_full.iloc[test_idx]
    y_tr, y_te = y_full.iloc[train_idx], y_full.iloc[test_idx]

    model = SVR(**svr_search.best_params_)
    model.fit(X_tr, y_tr)
    pred = model.predict(X_te)
    mae_f, rmse_f, da_f = fold_metrics(y_te, pred)

    fold_results.append({
        'fold': fold, 'train_size': len(train_idx), 'test_size': len(test_idx),
        'MAE': mae_f, 'RMSE': rmse_f, 'Directional Accuracy (%)': da_f
    })

fold_df = pd.DataFrame(fold_results)
display(fold_df)
print(f"\nAverage MAE across folds: {fold_df['MAE'].mean():.4f}")
print(f"Average RMSE across folds: {fold_df['RMSE'].mean():.4f}")
print(f"Average Directional Accuracy across folds: {fold_df['Directional Accuracy (%)'].mean():.2f}%")

"""## Generate and Export Model (Pickle)
Save the final fitted SVR model to a `.pkl` file, then reload it to confirm the export is valid.
"""

model_filename = 'svr_final_model.pkl'

with open(model_filename, 'wb') as file:
    pickle.dump(svr_final, file)

print(f"Model successfully saved to {model_filename}")

# Verify: reload and check type
with open(model_filename, 'rb') as file:
    loaded_svr_model = pickle.load(file)

print(f"Model successfully loaded. Type: {type(loaded_svr_model)}")
print(f"Loaded model parameters: {loaded_svr_model.get_params()}")