# -*- coding: utf-8 -*-
"""Copy of TCN+XGBoost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8hTtXKpzYPl6yAglGCDXHCobaTDDOzI

# Imports
- Import necessary libraries for implementing this model including TCN modelling, graph plotting and evaluation metrics
"""

# standard libraries
import warnings
warnings.filterwarnings('ignore')
import os

# data manipulation
import pandas as pd
import numpy as np

# visualization
import matplotlib.pyplot as plt

# machine learning
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.base import BaseEstimator, RegressorMixin

# TCN model
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# File handling
from google.colab import files
import pickle
import joblib

# feature importance
from sklearn.inspection import permutation_importance

"""# File Upload
- Uploading the train/test dataset

What need to be uploaded
- Train set: X_train_raw, y_train
- Test set: X_test_raw, y_test
- Model specfic files
  - xgboost_tuned.pkl (from xgboost modelling code file)
  - tcn_config.pkl (from TCN modelling code file)
  - best_tcn_model.pth (from TCN modelling code file)
  - preprocessors.pkl (from TCN modelling code file)

"""

# Run Local if Google Drive fails
uploaded = files.upload()

"""# Load Data
- Load the data from the uploaded dataset
- Ensure that the dataset is complete with no missing values
- The training dataset should include 2440 records
"""

# load files
X_train = pd.read_csv('X_train_raw.csv')
X_test = pd.read_csv('X_test_raw.csv')
y_train = pd.read_csv('y_train.csv').values.ravel()
y_test = pd.read_csv('y_test.csv').values.ravel()

# display information
print("=" * 60)
print("DATA LOADED SUCCESSFULLY")
print("=" * 60)
print(f"Training set: {X_train.shape[0]} samples, {X_train.shape[1]} features")
print(f"Test set: {X_test.shape[0]} samples, {X_test.shape[1]} features")
print(f"Target range: {y_train.min():.6f} to {y_train.max():.6f}")
print(f"\nFeature columns: {X_train.columns.tolist()}")
print(f"\nMissing values in training: {X_train.isnull().sum().sum()}")
print(f"Missing values in test: {X_test.isnull().sum().sum()}")
print("=" * 60)

"""# Defining TCN
Defines the **PyTorch Temporal Convolutional Network (TCN) architecture**.
- `TemporalBlock` implements 1D dilated causal convolutions with residual connections, ReLU activations, and dropout to capture long-range sequence dependencies without data leakage.
- `TCN class` stacks these blocks across increasing dilation rates and passes the final time step through a linear output layer for single-step target forecasting.
"""

class TemporalBlock(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, dilation, dropout=0.2):
        super().__init__()
        padding = (kernel_size - 1) * dilation
        self.conv1 = nn.Conv1d(in_channels, out_channels, kernel_size,
                               padding=padding, dilation=dilation)
        self.relu1 = nn.ReLU()
        self.dropout1 = nn.Dropout(dropout)
        self.conv2 = nn.Conv1d(out_channels, out_channels, kernel_size,
                               padding=padding, dilation=dilation)
        self.relu2 = nn.ReLU()
        self.dropout2 = nn.Dropout(dropout)
        self.downsample = nn.Conv1d(in_channels, out_channels, 1) if in_channels != out_channels else None
        self.init_weights()

    def init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv1d):
                nn.init.kaiming_normal_(m.weight, mode='fan_in', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)

    def forward(self, x):
        out = self.conv1(x)
        out = self.relu1(out)
        out = self.dropout1(out)
        out = self.conv2(out)
        out = self.relu2(out)
        out = self.dropout2(out)
        res = x if self.downsample is None else self.downsample(x)
        _, _, length = res.shape
        out = out[:, :, :length]
        return self.relu2(out + res)


class TCN(nn.Module):
    def __init__(self, input_dim, output_dim=1, num_channels=64, kernel_size=3, dilations=None, dropout=0.2):
        super().__init__()
        if dilations is None:
            dilations = [1, 2, 4, 8, 16]
        self.blocks = nn.ModuleList()
        in_ch = input_dim
        for d in dilations:
            self.blocks.append(TemporalBlock(in_ch, num_channels, kernel_size, d, dropout))
            in_ch = num_channels
        self.fc = nn.Linear(num_channels, output_dim)

    def forward(self, x):
        x = x.permute(0, 2, 1)
        for block in self.blocks:
            x = block(x)
        x = x[:, :, -1]
        return self.fc(x).squeeze(-1)

"""# Load Models
- Loads the XGBoost and TCN files including `xgboost_tuned.pkl`, `tcn_config.pkl`, `best_tcn_model.pth` and `preprocessors.pkl`
"""

# 1. Load XGBoost
with open('xgboost_tuned.pkl', 'rb') as f:
    xgb_model = pickle.load(f)

# 2. Load TCN config and rebuild model
with open('tcn_config.pkl', 'rb') as f:
    tcn_config = pickle.load(f)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tcn_model = TCN(**tcn_config)   # uses the TCN class defined in this notebook
tcn_model.load_state_dict(torch.load('best_tcn_model.pth', map_location=device))
tcn_model.to(device)
tcn_model.eval()

# 3. Load preprocessors
with open('preprocessors.pkl', 'rb') as f:
    preprocessors = pickle.load(f)

print("All models and preprocessors loaded.")

"""# TCN preprocessing
- Implements feature-level preprocessing for the TCN model
- Takes raw multi-feature rows and applies sequence-ready scaling: log-transform and Z-score standardization on prices, pre-fitted PowerTransformations on volume and rolling volatility metrics, and standard scaling on returns
- Returns a vectorized float32 array aligned with the TCN input dimensions
"""

def preprocess_for_tcn(raw_row, preprocessors):
    price, vol, ret, vol7, vol30, anomaly = raw_row
    price_log = np.log(price)
    price_scaled = (price_log - preprocessors['price_mean']) / preprocessors['price_std']
    vol_scaled   = preprocessors['pt_vol'].transform([[vol]])[0,0]
    vol7_scaled  = preprocessors['pt_vol7'].transform([[vol7]])[0,0]
    vol30_scaled = preprocessors['pt_vol30'].transform([[vol30]])[0,0]
    ret_scaled = preprocessors['scaler_return'].transform([[ret]])[0,0]
    return np.array([price_scaled, vol_scaled, ret_scaled, vol7_scaled, vol30_scaled, anomaly], dtype=np.float32)

"""# Helper Functions

## Predict dataset
- Constructs 30-day rolling sequence windows (seq_len = 30) and aligns targets for time-series forecasting
- Generates predictions for XGBoost using the latest raw feature vector and for TCN using preprocessed sequence tensors
- Combines model predictions via a weighted linear ensemble ($39\%$ TCN weight and $61\%$ XGBoost weight).
"""

SEQ_LEN = 30
TCN_WEIGHT = 0.39

def predict_dataset(X_raw, y_raw, seq_len=SEQ_LEN, tcn_weight=TCN_WEIGHT):
    """Creates windows and generates predictions for XGBoost, TCN, and Ensemble."""
    # 1. Build sequence windows
    X_windows, y_aligned = [], []
    for i in range(len(X_raw) - seq_len):
        X_windows.append(X_raw[i:i + seq_len])
        y_aligned.append(y_raw[i + seq_len])

    X_windows = np.array(X_windows)
    y_aligned = np.array(y_aligned)

    # 2. Get predictions
    xgb_preds, tcn_preds = [], []
    for window in X_windows:
        # XGBoost prediction
        latest_raw = window[-1].reshape(1, -1)
        xgb_preds.append(xgb_model.predict(latest_raw)[0])

        # TCN prediction
        scaled_window = np.array([preprocess_for_tcn(row, preprocessors) for row in window])
        tcn_input = torch.tensor(scaled_window, dtype=torch.float32).unsqueeze(0).to(device)
        with torch.no_grad():
            tcn_preds.append(tcn_model(tcn_input).item())

    xgb_preds = np.array(xgb_preds)
    tcn_preds = np.array(tcn_preds)
    ensemble_preds = tcn_weight * tcn_preds + (1 - tcn_weight) * xgb_preds

    return y_aligned, xgb_preds, tcn_preds, ensemble_preds

"""## Evaluation Function
- A function for defining the evaluation metrics used for evaluating the model performance
- Include `MAE`, `RMSE`, `Directional Accuracy` and `R²`
"""

def evaluate_and_print(y_true, xgb_preds, tcn_preds, ensemble_preds, title="PERFORMANCE"):
    """Calculates metrics and formats output."""
    def compute_metrics(y_true, y_pred):
        mae = mean_absolute_error(y_true, y_pred)
        rmse = np.sqrt(mean_squared_error(y_true, y_pred))
        da = np.mean((y_true > 0) == (y_pred > 0)) * 100
        r2 = r2_score(y_true, y_pred)
        return mae, rmse, da, r2  # <-- Add r2 here

    xgb_mae, xgb_rmse, xgb_da, xgb_r2 = compute_metrics(y_true, xgb_preds)
    tcn_mae, tcn_rmse, tcn_da, tcn_r2 = compute_metrics(y_true, tcn_preds)
    ens_mae, ens_rmse, ens_da, ens_r2 = compute_metrics(y_true, ensemble_preds)

    print("\n" + "=" * 70)
    print(f"FINAL {title.upper()}")
    print("=" * 60)
    print(f"XGBoost   : MAE = {xgb_mae:.4f}, RMSE = {xgb_rmse:.4f}, DA = {xgb_da:.4f}%, R2 = {xgb_r2:.4f}")
    print(f"TCN       : MAE = {tcn_mae:.4f}, RMSE = {tcn_rmse:.4f}, DA = {tcn_da:.4f}%, R2 = {tcn_r2:.4f}")
    print(f"Ensemble  : MAE = {ens_mae:.4f}, RMSE = {ens_rmse:.4f}, DA = {ens_da:.4f}%, R2 = {ens_r2:.4f}")
    print("=" * 70)

"""# Main Modelling for TCN+XGBoost

## Train
- Perform training on the model using X_train_raw and y_train
- Evaluate the performance of training
"""

y_train_aligned, xgb_tr_preds, tcn_tr_preds, ens_tr_preds = predict_dataset(X_train, y_train)
evaluate_and_print(y_train_aligned, xgb_tr_preds, tcn_tr_preds, ens_tr_preds, title="Train Performance")

"""## Test
- Perform training on the model using X_test_raw and y_test
- Use a 30 days lookback window obtain from X_train_raw
- Evaluate the performance of training
"""

X_test_padded = np.vstack([X_train[-SEQ_LEN:], X_test])
y_test_padded = np.concatenate([y_train[-SEQ_LEN:], y_test])
y_true_aligned, xgb_preds, tcn_preds, ensemble_preds = predict_dataset(X_test_padded, y_test_padded)
evaluate_and_print(y_true_aligned, xgb_preds, tcn_preds, ensemble_preds, title="Test Performance")

"""# Features Importance
- Shows the importance of each features used by the model
"""

# Load X_train_raw once for context padding
X_train_raw = pd.read_csv("X_train_raw.csv").values

# Extract feature names from X_test DataFrame
feature_names = X_test.columns.tolist()

# 3. Define EnsembleWrapper to handle 30-day sequence lookback padding
class EnsembleWrapper(BaseEstimator, RegressorMixin):
    def __init__(self, seq_len=SEQ_LEN, tcn_weight=TCN_WEIGHT):
        self.seq_len = seq_len
        self.tcn_weight = tcn_weight

    def fit(self, X, y=None):
        return self

    def predict(self, X):
        # Prepend last 30 rows of X_train so window start aligns with row 0 of X
        X_padded = np.vstack([X_train_raw[-self.seq_len:], X])
        dummy_y = np.zeros(len(X_padded))
        _, _, _, ens_preds = predict_dataset(
            X_padded, dummy_y, seq_len=self.seq_len, tcn_weight=self.tcn_weight
        )
        return ens_preds

# Instantiate wrapper
ensemble_estimator = EnsembleWrapper()

# Run Permutation Importance across X_test
result = permutation_importance(
    estimator=ensemble_estimator,
    X=X_test,
    y=y_true_aligned,
    scoring='neg_mean_squared_error',
    n_repeats=5,
    random_state=42
)

# Sort feature importances in descending order
sorted_importances_idx = result.importances_mean.argsort()[::-1]

# Format into DataFrame and display
permutation_importances = pd.DataFrame({
    'Feature': np.array(feature_names)[sorted_importances_idx],
    'Importance': result.importances_mean[sorted_importances_idx]
}).sort_values(by='Importance', ascending=False).reset_index(drop=True)

print('-------- XGBoost+TCN Feature Importance --------')
display(permutation_importances)

"""# Visualization

## Compare the Actual and Predicted Value for Exact_Return
- A line graph showing the predicted and actual value of the target variable,
"""

results_df = pd.DataFrame({
    'Actual': y_true_aligned,
    'Predicted': ensemble_preds,
    'Index': range(1, len(y_true_aligned) + 1)
})

# Create figure
fig, ax = plt.subplots(figsize=(14, 6))

# Plot lines
ax.plot(results_df['Index'], results_df['Actual'],
        label='Actual', linewidth=1.8, color='lightgrey')
ax.plot(results_df['Index'], results_df['Predicted'],
        label='Predicted', linewidth=1.8, color='orange')

# Labels and title
ax.set_xlabel('Test Sample Index', fontsize=12)
ax.set_ylabel('% Change', fontsize=12)
ax.set_title('Time Series: Actual vs Predicted', fontsize=14, fontweight='bold')

# Legend
ax.legend(fontsize=11)

# Grid
ax.grid(True, alpha=0.3, linestyle='--')

# Tight layout
plt.tight_layout()

plt.show()

"""## Cumulative Graph
- Shows the performance of a direction trading strategy driven by the XGBoost model against a standard Buy&Hold benchmark
"""

# Create signal: +1 if model predicts positive return, -1 if negative return
signal = np.where(ensemble_preds > 0, 1, -1)

# Strategy daily returns using exact aligned test targets
strategy_returns = signal * (y_true_aligned / 100)

# Cumulative returns
cum_actual = (1 + (y_true_aligned / 100)).cumprod() - 1
cum_strategy = (1 + strategy_returns).cumprod() - 1

# Plot Cumulative Strategy
plt.figure(figsize=(12, 6))
plt.plot(cum_actual * 100, label='Buy & Hold Asset Return (%)', color='gray', alpha=0.7)
plt.plot(cum_strategy * 100, label='TCN+XGBoost Directional Strategy Return (%)', color='green', linewidth=2)
plt.title('Cumulative Trading Strategy Performance vs. Benchmark', fontsize=14, fontweight='bold')
plt.xlabel('Trading Days', fontsize=12)
plt.ylabel('Cumulative Return (%)', fontsize=12)
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""# Generating and Exporting the pkl file
- Generates the pkl and json file based on the hyperparameter identified and
"""

class EnsembleModel(BaseEstimator, RegressorMixin):

  def __init__(
      self,
      xgb_model,
      tcn_model,
      preprocessors,
      seq_len=30,
      tcn_weight=0.39,
      device="cpu",
  ):
    self.xgb_model = xgb_model
    self.tcn_model = tcn_model
    self.preprocessors = preprocessors
    self.seq_len = seq_len
    self.tcn_weight = tcn_weight
    self.device = device

  def fit(self, X, y=None):
    return self

  def predict(self, X_raw):
    # Ensure raw input is numpy array
    if hasattr(X_raw, "values"):
      X_raw = X_raw.values

    # 1. Build sequence windows
    X_windows = []
    for i in range(len(X_raw) - self.seq_len):
      X_windows.append(X_raw[i : i + self.seq_len])
    X_windows = np.array(X_windows)

    if len(X_windows) == 0:
      return np.array([])

    xgb_preds, tcn_preds = [], []
    self.tcn_model.eval()

    # 2. Run predictions across windows
    for window in X_windows:
      # XGBoost prediction
      latest_raw = window[-1].reshape(1, -1)
      xgb_preds.append(self.xgb_model.predict(latest_raw)[0])

      # TCN prediction
      scaled_window = np.array([
          preprocess_for_tcn(row, self.preprocessors) for row in window
      ])
      tcn_input = (
          torch.tensor(scaled_window, dtype=torch.float32)
          .unsqueeze(0)
          .to(self.device)
      )

      with torch.no_grad():
        tcn_preds.append(self.tcn_model(tcn_input).item())

    xgb_preds = np.array(xgb_preds)
    tcn_preds = np.array(tcn_preds)

    # 3. Combine predictions
    ensemble_preds = (
        self.tcn_weight * tcn_preds + (1 - self.tcn_weight) * xgb_preds
    )
    return ensemble_preds


# Instantiate the wrapper with your trained assets
ensemble_estimator = EnsembleModel(
    xgb_model=xgb_model,
    tcn_model=tcn_model,
    preprocessors=preprocessors,
    seq_len=SEQ_LEN,
    tcn_weight=TCN_WEIGHT,
)

# Save the full estimator object directly
joblib.dump(ensemble_estimator, "ensemble_model.pkl")

# Save XGBoost natively as JSON (never corrupts)
ensemble_estimator.xgb_model.save_model("xgb_submodel.json")

# Save PyTorch TCN weights
torch.save(ensemble_estimator.tcn_model.state_dict(), "tcn_submodel.pth")

# Save preprocessors
joblib.dump(ensemble_estimator.preprocessors, "preprocessors.pkl")

files.download('xgb_submodel.json')
files.download('tcn_submodel.pth')
files.download('preprocessors.pkl')
files.download('ensemble_model.pkl')

import ipywidgets as widgets
from IPython.display import display, clear_output
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import joblib
from sklearn.base import BaseEstimator, RegressorMixin

# Removed redundant class definitions and helper function definitions
# TemporalBlock, TCN, EnsembleModel, and preprocess_for_tcn should be defined
# only once earlier in the notebook, e.g., in cell oixEsVsE70VO for TCN
# classes and HqjAuozi0p5q for EnsembleModel, and JMrE7vvX77NA for preprocess_for_tcn.

# ==========================================
# 1. LOAD TEST DATA & ENSEMBLE CHECKPOINT
# ==========================================
try:
    X_train_raw_full = pd.read_csv("X_train_raw.csv").values
    X_test_raw_full = pd.read_csv("X_test_raw.csv").values
    ensemble_estimator = joblib.load("ensemble_model.pkl")
    print("✅ Ensemble model and data successfully loaded into Colab.")
except FileNotFoundError:
    print("❌ ERROR: Please ensure 'ensemble_model.pkl', 'X_train_raw.csv', and 'X_test_raw.csv' are uploaded.")
except EOFError:
    print("❌ ERROR: 'ensemble_model.pkl' could not be loaded. This typically indicates a corrupted file.")

SEQ_LEN = getattr(ensemble_estimator, "seq_len", 30)
X_combined = np.vstack([X_train_raw_full[-SEQ_LEN:], X_test_raw_full])

# ==========================================
# 2. BUILD THE USER INTERFACE WIDGETS
# ==========================================
print("\n=== 🔮 TCN + XGBOOST ENSEMBLE: MANUAL INPUT SANDBOX ===")

price_input = widgets.FloatText(value=135793.0, description='Price Lag1 (₹):', style={'description_width': 'initial'})
vol_input = widgets.FloatText(value=51877.0, description='Volume Lag1:', style={'description_width': 'initial'})
ret_input = widgets.FloatText(value=0.02, description='Return Lag1 (%):', style={'description_width': 'initial'})
vol7_input = widgets.FloatText(value=0.85, description='Vol 7d:', style={'description_width': 'initial'})
vol30_input = widgets.FloatText(value=0.99, description='Vol 30d:', style={'description_width': 'initial'})
anomaly_input = widgets.Dropdown(options=[('Normal Day (0)', 0), ('Anomaly (1)', 1)], value=0, description='Is Anomaly:', style={'description_width': 'initial'})

predict_btn = widgets.Button(description="Generate Ensemble Prediction", button_style='success', icon='check')
output_display = widgets.Output()

left_box = widgets.VBox([price_input, ret_input, vol7_input])
right_box = widgets.VBox([vol_input, anomaly_input, vol30_input])
ui = widgets.HBox([left_box, right_box])

# ==========================================
# 3. DEFINE THE PREDICTION LOGIC
# ==========================================
def on_predict_click(b):
    with output_display:
        clear_output()
        print("Processing custom input and attaching to historical 29-day sequence...")

        # 1. Capture values from UI
        p_lag = price_input.value
        v_lag = vol_input.value
        r_lag = ret_input.value
        v7 = vol7_input.value
        v30 = vol30_input.value
        is_anom = anomaly_input.value

        # Create the custom row array
        custom_row = np.array([p_lag, v_lag, r_lag, v7, v30, is_anom])

        try:
            # 2. Build the 30-day window
            # Take the very last 29 days from the test set as background context
            history_29_days = X_combined[-(SEQ_LEN - 1):]

            # Stitch the custom manual input to the end to make 30 days
            window = np.vstack([history_29_days, custom_row])

            # --- A. XGBoost Sub-model Prediction ---
            # XGBoost prediction uses the latest raw feature vector[cite: 4].
            latest_raw = custom_row.reshape(1, -1)
            xgb_pred = ensemble_estimator.xgb_model.predict(latest_raw)[0]

            # --- B. TCN Sub-model Prediction ---
            # TCN prediction uses preprocessed sequence tensors[cite: 4].
            scaled_window = np.array([
                preprocess_for_tcn(row, ensemble_estimator.preprocessors) for row in window
            ])
            tcn_input = torch.tensor(scaled_window, dtype=torch.float32).unsqueeze(0).to(ensemble_estimator.device)

            ensemble_estimator.tcn_model.eval()
            with torch.no_grad():
                tcn_pred = ensemble_estimator.tcn_model(tcn_input).item()

            # --- C. Weighted Ensemble Combination ---
            # Combines model predictions via a weighted linear ensemble[cite: 4].
            tcn_weight = ensemble_estimator.tcn_weight
            ensemble_pred = tcn_weight * tcn_pred + (1 - tcn_weight) * xgb_pred

            # --- D. Price Reconstruction ---
            pred_price = p_lag * (1 + (ensemble_pred / 100))

            # --- E. Display Results ---
            print("-" * 45)
            print(f"✅ ENSEMBLE PREDICTION SUCCESSFUL")
            print(f"-> XGBoost Sub-Prediction    : {xgb_pred:+.4f}%")
            print(f"-> TCN Sub-Prediction        : {tcn_pred:+.4f}%")
            print(f"-> Combined Ensemble Return  : {ensemble_pred:+.4f}%")
            print(f"-> Reconstructed Next Price  : ₹{pred_price:,.2f}")
            print("-" * 45)

        except Exception as e:
            print(f"❌ Error during ensemble prediction: {e}")

predict_btn.on_click(on_predict_click)
display(ui, predict_btn, output_display)